data:
  raw_dir: data/raw
  processed_dir: data/processed
  interim_dir: data/interim

ingest:
  item_views: train-item-views.csv
  clicks: train-clicks.csv
  purchases: train-purchases.csv
  queries: train-queries.csv
  products: products.csv
  product_categories: product-categories.csv
  # min_interactions: 5 # filter users with fewer interactions than this
