apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recsys-model-cache
  namespace: recsys
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: recsys-efs-sc
  resources:
    requests:
      storage: 20Gi
