apiVersion: v1
kind: Secret
metadata:
  name: recsys-secrets
  namespace: recsys
type: Opaque
stringData:
  api-keys: "replace-with-comma-separated-api-keys"
  dagshub-user-token: "replace-with-dagshub-token"

